# my global config
  global:
    scrape_interval: 10s
    evaluation_interval: 10s
 # Alertmanager configuration
 alerting:
   alertmanagers:
     - static_configs:
         - targets:
           # - alertmanager:9093

scrape_configs:

  - job_name: "prometheus"
  static_configs:
    - targets: ["localhost:9090"]

  - job_name: "ultrafeeder"
  static_configs:
    - targets: ["GS_BRIDGE_IP:9273", "GS_BRIDGE_IP:9274"]

  remote_write:
  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
    basic_auth:
      username: 1488847
      GS_PFIELD: GS_PWORD
